AWSTemplateFormatVersion: '2010-09-09'
Description: 'HTTPS CloudFront Distribution for AllSenses Demo'

Resources:
  # CloudFront Distribution for HTTPS Access
  DemoCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: allsenses-mvp1-demo-website.s3-website-us-east-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: mvp1-complete-demo.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  HTTPSUrl:
    Description: 'HTTPS URL for Hackathon Demo'
    Value: !Sub 'https://${DemoCloudFrontDistribution.DomainName}/mvp1-complete-demo.html'
    Export:
      Name: !Sub "${AWS::StackName}-HTTPSUrl"
  
  CloudFrontDomain:
    Description: 'CloudFront Distribution Domain'
    Value: !GetAtt DemoCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDomain"