AWSTemplateFormatVersion: '2010-09-09'
Description: 'AllSenseAI Clean Core Infrastructure'

Resources:
  # DynamoDB Table for User Profiles
  UserProfilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AllSenseAI-UserProfiles
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  # S3 Bucket for Audio Samples (temporary storage)
  AudioSamplesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "allsenseai-audio-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAudioAfter24Hours
            Status: Enabled
            ExpirationInDays: 1

  # Lambda Execution Role
  AllSenseAILambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AllSenseAI-Lambda-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AllSenseAIPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt UserProfilesTable.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub "${AudioSamplesBucket}/*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "*"
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  UserProfilesTableName:
    Description: 'DynamoDB Table for User Profiles'
    Value: !Ref UserProfilesTable
    Export:
      Name: AllSenseAI-UserProfilesTable

  AudioBucketName:
    Description: 'S3 Bucket for Audio Samples'
    Value: !Ref AudioSamplesBucket
    Export:
      Name: AllSenseAI-AudioBucket

  LambdaRoleArn:
    Description: 'Lambda Execution Role ARN'
    Value: !GetAtt AllSenseAILambdaRole.Arn
    Export:
      Name: AllSenseAI-LambdaRole